using SimpleValidator.ViewModels.Commands;
using SimpleValidator.ViewModels.Validators;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SimpleValidator.ViewModels
{
    public abstract class BaseViewModel : INotifyPropertyChanged, INotifyDataErrorInfo
    {
        public BaseViewModel()
        {
            this.Errors = new Dictionary<string, List<string>>();
            this.ValidationRules = new Dictionary<string, List<IValidationRule>>();
        }

        /// <summary>
        /// A global lock for property checks so prevent locking on different instances of expressions.
        /// Considering how fast this check will always be it isn't an issue to globally lock all callers.
        /// </summary>
        protected object mPropertyValueCheckLock = new object();


        /// <summary>
        /// The event that is fired when any child property changes its value
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Call this to fire a <see \cref="PropertyChanged"/> event
        /// </summary>
        /// <param \name=\"name\"></param>
        // public event PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            this.PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        #region Validation implementation

        // Validation method. 
        // Is called from each property which needs to validate its value.
        // Because the parameter 'propertyName' is decorated with the 'CallerMemberName' attribute.
        // this parameter is automatically generated by the compiler. 
        // The caller only needs to pass in the 'propertyValue', if the caller is the target property's set method.
        protected bool ValidateProperty<TValue>(TValue propertyValue, RelayCommand relayCommand = null,
            [CallerMemberName] string propertyName = null)
        {
            // Clear previous errors of the current property to be validated 
            this.Errors.Remove(propertyName);
            OnErrorsChanged(propertyName);

            if (this.ValidationRules.TryGetValue(propertyName, out List<IValidationRule> propertyValidationRules))
            {
                // Apply all the rules that are associated with the current property and validate the property's value
                if (this.ValidationMode == ValidationMode.SuppressInvalidInput)
                {
                    return propertyValidationRules
                        .Select(validationRule => validationRule.Validate(propertyValue, CultureInfo.CurrentCulture))
                        .All(result => result.Status != ValidationResultStatus.Error);
                }

                List<ValidationResult> invalidResults = propertyValidationRules
                    .Select(validationRule => validationRule.Validate(propertyValue, CultureInfo.CurrentCulture))
                    .Where(result => result.Status == ValidationResultStatus.Error || result.Status == ValidationResultStatus.Warning)
                    .ToList();

                invalidResults.ForEach(
                    invalidResult => AddError(
                        propertyName,
                        invalidResult.Message,
                        invalidResult.Status == ValidationResultStatus.Warning));


                // Force all subscribers of the SaveCommand to re-evaluate CanExecute
                (relayCommand as RelayCommand).InvalidateCommand();

                return invalidResults.All(invalidResult => invalidResult.Status != ValidationResultStatus.Error);
            }

            // No rules found for the current property
            return true;
        }

        // Adds the specified error to the errors collection if it is not 
        // already present, inserting it in the first position if 'isWarning' is 
        // false. Raises the ErrorsChanged event if the Errors collection changes. 
        // A property can have multiple errors.
        private void AddError(string propertyName, string errorMessage, bool isWarning = false)
        {
            if (!this.Errors.TryGetValue(propertyName, out List<string> propertyErrors))
            {
                propertyErrors = new List<string>();
                this.Errors[propertyName] = propertyErrors;
            }

            if (!propertyErrors.Contains(errorMessage))
            {
                if (isWarning)
                {
                    // Move warnings to the end
                    propertyErrors.Add(errorMessage);
                }
                else
                {
                    propertyErrors.Insert(0, errorMessage);
                }
                OnErrorsChanged(propertyName);
            }
        }

        public bool PropertyHasErrors(string propertyName) =>
            this.Errors.TryGetValue(propertyName, out List<string> propertyErrors) && propertyErrors.Any();

        public event EventHandler<DataErrorsChangedEventArgs> ErrorsChanged;

        // Returns all errors of a property. If the argument is 'null' instead of the property's name, 
        // then the method will return all errors of all properties.
        public IEnumerable GetErrors(string propertyName)
          => string.IsNullOrWhiteSpace(propertyName)
            ? this.Errors.SelectMany(entry => entry.Value)
            : this.Errors.TryGetValue(propertyName, out List<string> errors)
              ? errors
              : new List<string>();

        // Returns if the view model has any invalid property
        public bool HasErrors => this.Errors.Any();

        protected virtual void OnErrorsChanged(string propertyName)
        {
            this.ErrorsChanged?.Invoke(this, new DataErrorsChangedEventArgs(propertyName));
        }

        // Maps a property name to a list of errors that belong to this property
        private Dictionary<string, List<string>> Errors { get; }

        // Maps a property name to a list of ValidationRules that belong to this property
        protected Dictionary<string, List<IValidationRule>> ValidationRules { get; private set; }

        private ValidationMode ValidationMode { get; set; }

        #endregion Validation implementation

    }
}
